version: '3'
services:
    web:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./app:/app
        environment:
            PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
            XDEBUG_CONFIG: "mode=debug client_host=host.docker.internal discover_client_host=true client_port=9003"
