version: '3'
services:
    web:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        expose:
            - 9000
        volumes:
            - ./app:/app